### ISSUE TITLE
use kmsgrab and string for all vaapi capable gpus

### ISSUE THREAD

**Issue by nicman23** [kokoko3k/ssh-rdp#2]
`ffmpeg -framerate 60 -f kmsgrab -i - -vaapi_device /dev/dri/renderD128 -vf 'hwmap=derive_device=vaapi,scale_vaapi=w=1920:h=1080:format=nv12' -c:v h264_vaapi -qp:v 26 -bf 0 -tune zerolatency -f mpegts - | nc -l -p 9000`

this is a zero copy encode (everything stays in the gpu) and supports wayland

**Comment by kokoko3k** [comment]
Hi, sorry for the delay.
I just merged amdgpu and intelgpu into the same encoding string, which is basically vaapi and x11grab.
Being on nvidia myself, i'm unable to test your command, nvidia proprietary driver just does not support kmsgrab, but apart from that, the script would require a big refactoring to support kmsgrab, since it now performs optional crop that wouldn't be possible with a zero copy approach (and even if it would be supported by some vaapi filter, as said, it would require me to think again how to integrate it into the existing -pretty tight- code without break "legacy" functionalities")
I know it is not ideal.

Are you able to measure an inferior load on the server when performing kmsgrab vs x11grab? How much?

**Comment by nicman23** [comment]
it is not the load that is the benefit but rather the lower latency because the frames do not have to go through the cpu. i ll fork and test stuff

**Comment by nicman23** [comment]
this gives me lower than 10 ms latency on an amd rx580

host: `ffmpeg  -r 120 -f kmsgrab -i - -vaapi_device /dev/dri/renderD128 -vf 'hwmap=derive_device=vaapi,scale_vaapi=w=2560:h=1080:format=nv12' -c:v h264_vaapi -qp 28 -profile 100 -bufsize 0 -f_strict experimental -syncpoints none -f mpegts udp://192.168.0.247:12345`

client: `mpv --untimed -audio-buffer=0 -vd-lavc-threads=1 -cache-pause=no -demuxer-lavf-o-add=fflags=+nobuffer -demuxer-lavf-probe-info=nostreams -demuxer-lavf-analyzeduration=0.1 -video-sync=desync -interpolation=no -video-latency-hacks=yes -stream-buffer-size=4k --cache-secs=0 --demuxer-readahead-secs=0 --no-correct-pts --fps=60 --framedrop=decoder+vo udp://0.0.0.0:12345`

it is really really fast but it is udp which i do not know if you want to support. there is something weird with hevc_vaapi that makes decoding to have a 500ms flat latency which h264_vaapi does not have.

however there is a mesa bug with h264_vaapi which makes ffmpeg to encode to ~ 40-45 fps for me - while hevc_vaapi has a stable 60.

it is a bit of a mess really but the above 2 commands are damn near zero latency. this post is more about what i found out playing with ffmpeg for a couple of days than a feature request.

**Comment by kokoko3k** [comment]
Interesting.
I played with kmsgrab, but faced some breaking things:
1) on my intel igp, i get the following bug about color levels: https://trac.ffmpeg.org/ticket/8941
do you experience something similar?
2) hardware cursor (mouse) is not grabbed. One may resort to a software cursor, but i fear pageflipping would not work then 

Also, i can't spot a latency reduction versus my prevoius attempts, by testing locally that way:
```ssh-rdp.sh -s 127.0.0.1 -u koko -d 0.0 -r AUTO -f 60 --videoenc amdgpu --audioenc opus -v 10000 -a 128```

As for mpv, i think most of the options you use are in the low-latency profile.

Udp is nice, but requires network setup/port forwarding or hole punching, ssh tunnel is much more straightforward.

--edit
I forgot to say that i think it is not worth to try to squeeze lower latency from the grab part.
This is because if i try the long path (x11grab + nvenc) i've really (really!) no visual latency (nvidie encoder is particular good)

Do you have a way to measure latency?

**Comment by nicman23** [comment]
i measure latency by ffmpeg frames (from the ffmpeg command output) taking 2 simultaneous screenshots of both local and remote screens. i do not know why but with the defaults ssh-rdp had latency on the seconds scale with the same computers / network.

udp is nice for me as:
* i do not have any way to stream outside from my local net anyways (nonexistent upload speed)
* the client and the host can be running async

e: i was gaming today with the above (fallout 3) and it was very playable if not 100% perfect. probably better than steam in home streaming - which is what i am aiming at because steam has no arm builds

**Comment by kokoko3k** [comment]
> i measure latency by ffmpeg frames (from the ffmpeg command output) taking 2 simultaneous screenshots of both local and remote screens. i do not know why but with the defaults ssh-rdp had latency on the seconds scale with the same computers / network.

That's weird, what is the system you're streaming to? Would it be possible that it is not fast enough to decrypt the ssh stream in realtime?
What about if you test on the gaming machine entirely, i mean localhost to localhost/picture in picture ?

```ssh-rdp.sh -s 127.0.0.1 -u `whoami` -d 0.0 -r AUTO -f 60 --videoenc amdgpu --audioenc opus -v 10000 -a 128```

**Comment by nicman23** [comment]
it was a quad sandy bridge laptop which i also used with the udp streams. might be old but it is adequate. 

localhost streaming seems to be working ok.

**Comment by kokoko3k** [comment]
Since you spoke about arm steam builds, i was referring to the power of the (arm) client machine.
But maybe i misunderstood.

**Comment by nicman23** [comment]
ah ok, no all my testing are from a amd ryzen + rx580 to a i7 2600QM laptop.

**Comment by kokoko3k** [comment]
Well, that's very strange, since i can use ssh to stream from/to less powerfull machines over the internet (100MBps uplinks) and even through vpns with latencies more or less equals to the network ones.

**Comment by kokoko3k** [comment]
You may want to try the latest commit, probably it has nothing to do with your findings (ssh/tcp versus udp), but still i just forgot to disable bframes, now i did it.

**Comment by kokoko3k** [comment]
I made some precise latency measurements and found something unexpected.

I started a counter in a window (millisec precision): 
```while true ; do echo  $(($(date +%s%N)/10000000)) ; sleep 0.001 ; done```
...then i started the grab and made a screenshot to just compare the numbers in the real window and in the grabbed one, those are the results:
```
Preset    |   real  |   captured  | diff | frame lag@60hz
-------------------------------------------------------------
amdgpu    | ...0705 | ...0705     | 0    | 0
cpu       | ...4472 | ...4467     | 5    | 1
intelgpu  | ...2542 | ...2538     | 4    | 1
nvgpu     | ...6717 | ...6717     | 0    | 0
zerocopy1 | ...4656 | ...4652     | 4    | 1
zerocopy2 | ...6971 | ...6966     | 5    | 1
```

Now, since my display is a mere 60hz, i cannot measure anything under 16.7ms, so the real value to be read is:
difference = 0  ==> no frame lag
0 < difference < 17 ==> 1 frame lag

Faster presets were the ones which use x11grab and an hardware encoder (less than 10ms == 100fps with no lag on localhost)
cpu and intelgpu are slower because they involves the cpu (intelgpu uses cpu to do colorspace conversion).
but zerocopy is unexpectedly as slow.
zerocopy1 and zerocopy2 are not included in ssh-rdp.sh; well, zerocopy1 is, but commented, and the setting used are:
```
zerocopy1:
ffmpeg -nostdin  -loglevel warning  -y -framerate 60 -f kmsgrab -i -  -sws_flags bilinear -b:v 20000k -maxrate 20000k -vf hwmap=derive_device=vaapi,crop=1920:1080:0:0,scale_vaapi=1920:1080:format=nv12 -c:v h264_vaapi -bf 0 -f_strict experimental -syncpoints none -f nut - | mpv --untimed --profile=low-latency -
zerocopy2:
ffmpeg -nostdin  -loglevel warning  -y -framerate 60 -f kmsgrab -i -  -sws_flags bilinear -b:v 20000k -maxrate 20000k  -vf hwmap=derive_device=vaapi,scale_vaapi=format=nv12 -c:v h264_vaapi -bf 0 -f_strict experimental -syncpoints none -f nut - | mpv --untimed --profile=low-latency -
```

**Comment by nicman23** [comment]
that is very interesting i ll run tests of my own to see what is really going on. i ll try to do the above with remote and host by syncing their clocks

also you can safely push most 60hz displays to 75 with cvt12 (https://github.com/kevinlekiller/cvt_modeline_calculator_12)

**Comment by kokoko3k** [comment]
Yeah, thanks, i already tried with gtf in the past and couldn't reach 74hz, cvt12 seems to do the same.
Also, given i don't use TN panels, but prefer VA ones (deep blacks!) even over ips ones, the lcd shutter speed is not that low, so i can't see much improvements in pushing the monitor refresh rate.
Usually, i do the opposite, i downclock it to 50hz because it gives me less stutter/more consistent frame rates, at a price of higher latency of course.

**Comment by nicman23** [comment]
```
echo;
while true;
do echo -e "\033[1A"`date +%s%N`;
done | tee >(nc -u $host 9000) >(nc -u $remote 9000) > /dev/null
```

this is my probably overkill solution to having "real" "time" on both machines, still need to do the actual testing.

**Comment by kokoko3k** [comment]
There is a new "zerocopy" encoder in the list of supported ones.
relevant options follow:
```
-f kmsgrab 
-vf hwmap=derive_device=vaapi,crop="$RES:$OFFSET",scale_vaapi="$NEWRES":format=nv12 -c:v h264_vaapi -bf 0  -b:v "$VIDEO_BITRATE_MAX"k  -maxrate "$VIDEO_BITRATE_MAX"k
```
I managed to hack it into the script in a way i don't like too much but anyway it works and supports cropping and scaling without using the cpu at all.
...but as said, it doesn't work that well on my intel+nvidia (via render offload) system.
-edit-
Well, actually it performs better than x11grab+vaapi, but worse than nvenc.
Probably it is just a matter of my igp (haswell) not powerfull enough to take frames from nvidia card and encode them at the same time (indeed, cpu usage is under 100%, but load average is over the number of cores, so probably the system is struggling).
Let me know how how it works for you!.
Also, are you under wayland? Is the mouse cursor visible?
