### ISSUE TITLE
Cannot connect to a logged off remote session

### ISSUE THREAD

**Issue by adocampo** [kokoko3k/ssh-rdp#6]
Hi there, 

ssh-rdp cannot connect to a remote session when the user has logged off or the computer just booted up (ie: when DM is present). 

I've tried with sddm.

The error is the next one:
```bash
./ssh-rdp.sh --user sysops --server 192.168.10.70  -f 60 -a 128 -v 10000
[..] Starting ssh multiplexed connection
[OK] Started ssh multiplexed connection
[..] Checking required executables...
[OK] Checked required executables

[..] Checking input devices...
[OK] Device ready       : SINOWEALTH Wired Gaming Mouse
     add event device for SINOWEALTH Wired Gaming Mouse: event2
     add event device for SINOWEALTH Wired Gaming Mouse: event3
[OK] Device ready       : Corsair Corsair STRAFE RGB Gaming Keyboard
     add event device for Corsair Corsair STRAFE RGB Gaming Keyboard: event18
     add event device for Corsair Corsair STRAFE RGB Gaming Keyboard: event19
     add event device for Corsair Corsair STRAFE RGB Gaming Keyboard: event20
     add event device for Corsair Corsair STRAFE RGB Gaming Keyboard: event21
[..] Reading hotkey file /home/malevolent/.config/ssh-rdp.input.hk.config
[OK] GRAB_HOTKEY=119
[OK] FULLSCREENSWITCH_HOTKEY=70

[..] Setting up input loop and forwarding devices
     forward input from device event2...
     forward input from device event3...
     forward input from device event18...
     forward input from device event19...
     forward input from device event20...
     forward input from device event21...

[..] Starting netevent daemon with script /tmp/nescript19145
added device dev1
added device dev2
added device mykbd3
added hotkey 1:119:1 for device 2
added hotkey 1:119:0 for device 2
added hotkey 1:70:1 for device 2
added hotkey 1:70:0 for device 2
added device mykbd4
added hotkey 1:119:1 for device 3
added hotkey 1:119:0 for device 3
added hotkey 1:70:1 for device 3
added hotkey 1:70:0 for device 3
added device mykbd5
added hotkey 1:119:1 for device 4
added hotkey 1:119:0 for device 4
added hotkey 1:70:1 for device 4
added hotkey 1:70:0 for device 4
added device mykbd6
added hotkey 1:119:1 for device 5
added hotkey 1:119:0 for device 5
added hotkey 1:70:1 for device 5
added hotkey 1:70:0 for device 5
added output myremote

[..] Trying to connect to sysops@192.168.10.70:22
     and stream display :0
     with size AUTO and offset: +0,0

[..] Guessing audio capture device
[WW] Guessed audio capture source: alsa_output.pci-0000_02_0c.0.analog-stereo.monitor

[..] Guessing remote resolution
Invalid MIT-MAGIC-COOKIE-1 keyxdpyinfo:  unable to open display ":0.0".
[WW] Auto grab resolution: 

[..] Start audio streaming...
[..] Start video streaming...
[NULL @ 0x564f297656c0] Requested output format 'x11grab' is not a suitable output format
:0.0+0,0: Invalid argument
[file] Reading from stdin...
Failed to recognize file format.

Exiting... (Errors when loading file)
pipe:: Invalid data found when processing input
interrupted
interrupted
shutting down
```

In order to make it work, I need to physically sit in front of the remote computer (or in the case of a VM, enter the console) and log in the user, then I can safely lock the computer, as locking window is part of the desktop itself.

Is on the roadmap any kind of support for DMs (I don't mind using another DM if sddm is the one isn't working)

PS: this is an awesome piece of software. It simply leaves other remote desktop programs as mere toys, in terms of performance.

**Comment by kokoko3k** [comment]
Mmmh, right.
I could look into it in a couple of days.
Meanwhile, does the remote dm run wayland or Xorg?

**Comment by adocampo** [comment]
Xorg

**Comment by kokoko3k** [comment]
Ok, here is the issue:
ssh-rdp uses ssh for everything by design, and since the display manager is run by some specific user, one could try to login by impersonating it.
But usually, they are sddm,gdm... which wont allow remote ssh logins, of course, so we are left out in the cold.
Another option would be to use ssh-rdp as root, but even that is a bad idea, so...

However, there is an alternative: using kmsgrab, (with his own drawback).
For testing purposes ssh-rdp has an experimental "zerocopy" parameter to be passed to --videoenc option.
By using that, you ask ffmpeg to use the kmsgrab grab method, which in turns bypass x11 and grab the KMS scanout.

However, It is not all bells and whistles:
1) It won't work with with nvidia blob
(you can workaround that by using an integrated intel gpu or an amd apu gpu and offload nvidia with render offload)
2) it won't capture the mouse cursor
(you would have to login by using keyboard only and switch fields with TAB)
3) It requires ffmpeg to have elevated privileges
(run sudo setcap cap_sys_admin+ep /usr/bin/ffmpeg on the server after every ffmpeg update)
4) it is experimental and i cannot say it will work for you :)
(try...)

Another option would be to remotely start X11vnc temporally on the server, and use vnc just to login.

**Comment by kokoko3k** [comment]
If there is more to say, feel free to reopen.
